# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "soVKH4Rz0L1mx+hPsG59P4/QS4L673fa7T3tMBkuZJxPoc/RsEbu77iulmiOytZu3UYuDSWIVFimv2jEb4N3hU+IFV9Eoo272pvYa0RVTQ5bXzVcV8U1scNkMQy8XypJ5F86Naa5An+DICIYrVbKbbXkuwVbzaTwkbteTU6SY1y3mNw+QZS/6XpxH0Au8PAtzQSKVny0YgVJhhHMFGbRV+vvItWX04WZuVmomf0VKoD1hJ993AeCKM9YPbECik4Rahumb4o+fJvVXXLlENwzZhM1UOkV95uX92d0lVJiv6gz8GrzIxGRtVd/8nOh2jBrlZEUVp8tE96/AyCmIBKzEAPLJx/gCuCLWsRcGNAO+yWAySbnu5fvAHP/hQgYIaDfg8maIqqgIE0qkPL3wPNTciMc+kyT5Mj7NU6O5Khk6CN7XAwKD1hIxZq8gttOSBZ6slVRccQEbPpDz3YW8a5lxYzgD/Q1SN5Fs5acJf20CYHp+kcfN2Kb41jkI9R7z0++pRL7NfgVHkLrIPmZQv7OKjNqOA2hWKoMHIHtA7Hma1eQOLQJZ5NvzUtqPQOdmttrcDoyBdkYIw+cUus0mFOCgqiMLOKB7Or/7Vjt/ZN4WdfRkJgdC9TmMy8LjHnrNfegW2Gt9/begxGiqLa90Jf/z9sbuGAuVSND0hjo0E+AJ1U="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
