# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic
os:
  - linux-ppc64le
  - osx
dist: xenial      # power jobs only on ubuntu-xenial distribution
sudo: false       # deploy on workers with docker backend

osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "N9Xf9IIu4Jmi7d59tyHB7b3ihRRj/mFM4pNNRBIdvcMBEjuWqvHWtlbie4aqTyIwXfttWLyR65kc6s01sHHGFkjLsWcoc2ikfTHP2SpE+XhqcRHm/l5R2shPZ7dICS37i0jo+MhRebkGR1H3iOfvykt32xpv/FkTl8JWS92vuY2JdbfENEN1OQwDTq5ZJIHH8qf/c4gS7LMggK7l1g2OrBwuUrDyBbxNyMNTX/nvjO+jXkECWPSWmEXNSqwt0hZG7CQk8kmmR/pSf5wItZ+jGxgiRDfldrhkCZuKwU48OjmFZgOkPfoukhtUNXu2xXrJHX5ot+iKC9ZPIK+dIWkIbBm+kaos6N3fpEJwrULMr9E4ywpx7VIx0+RYsl4hMO0U1YIrx2qko5jG6yckIP1dOX47Y82n7bMs626f3N3lXQZ+nWiVCIOILUxmzPxK2GVMs7wPd/iXXZhr/n+h3eORBcOogbIH2hPfm3RM3G0ye9fMiBrl7b8zR11lLL02h8CtF/5bnZk4CLkdFwYq7oH9f+NP66nfS9FO5ahiZ8gMPSb+wjbTDLMWszBF3tiTLnCtLT0N33uLAADf7RZ2hX5hrBrG7PTHroIhrNhxL8mTIQHYFgV5Sf+RvJXuUqewaFCPRP6HV8HSqzuWoWI9s2slvSFVte315x6jVmcGc3a6bxA="


before_install:
    # Remove homebrew.
    - |
      if [ "$TRAVIS_OS_NAME" != "linux-ppc64le" ]; then
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
      fi

install:
    # Install Miniconda.
    - |
      if [ "$TRAVIS_OS_NAME" != "linux-ppc64le" ]; then
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
      else
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-Linux-ppc64le.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b -p $HOME/miniconda
      fi

    # Configure conda.
    - |
      if [ "$TRAVIS_OS_NAME" != "linux-ppc64le" ]; then
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup
      else
      echo "Configuring conda."
      export PATH="$HOME/miniconda/bin:$PATH"
      hash -r 
      conda config --set always_yes yes --set changeps1 no  
      conda update -q conda
      conda info -a
      conda install -n root conda-build      
      fi
      
script:
  - conda build ./recipe

  - |
    if [ "$TRAVIS_OS_NAME" != "linux-ppc64le" ]; then
    upload_or_check_non_existence ./recipe conda-forge --channel=main
    fi
