travis:
  secure:
    BINSTAR_TOKEN: soVKH4Rz0L1mx+hPsG59P4/QS4L673fa7T3tMBkuZJxPoc/RsEbu77iulmiOytZu3UYuDSWIVFimv2jEb4N3hU+IFV9Eoo272pvYa0RVTQ5bXzVcV8U1scNkMQy8XypJ5F86Naa5An+DICIYrVbKbbXkuwVbzaTwkbteTU6SY1y3mNw+QZS/6XpxH0Au8PAtzQSKVny0YgVJhhHMFGbRV+vvItWX04WZuVmomf0VKoD1hJ993AeCKM9YPbECik4Rahumb4o+fJvVXXLlENwzZhM1UOkV95uX92d0lVJiv6gz8GrzIxGRtVd/8nOh2jBrlZEUVp8tE96/AyCmIBKzEAPLJx/gCuCLWsRcGNAO+yWAySbnu5fvAHP/hQgYIaDfg8maIqqgIE0qkPL3wPNTciMc+kyT5Mj7NU6O5Khk6CN7XAwKD1hIxZq8gttOSBZ6slVRccQEbPpDz3YW8a5lxYzgD/Q1SN5Fs5acJf20CYHp+kcfN2Kb41jkI9R7z0++pRL7NfgVHkLrIPmZQv7OKjNqOA2hWKoMHIHtA7Hma1eQOLQJZ5NvzUtqPQOdmttrcDoyBdkYIw+cUus0mFOCgqiMLOKB7Or/7Vjt/ZN4WdfRkJgdC9TmMy8LjHnrNfegW2Gt9/begxGiqLa90Jf/z9sbuGAuVSND0hjo0E+AJ1U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
